const HIDE_ADD_USER_MODAL = '@@user/HIDE_ADD_USER_MODAL';
const SHOW_ADD_USER_MODAL = '@@user/SHOW_ADD_USER_MODAL';
const SHOW_EDIT_USER_MODAL = '@@user/SHOW_EDIT_USER_MODAL';
const HIDE_EDIT_USER_MODAL = '@@user/HIDE_EDIT_USER_MODAL';

export default {
    HIDE_EDIT_USER_MODAL,
    HIDE_ADD_USER_MODAL,
    SHOW_EDIT_USER_MODAL,
    SHOW_ADD_USER_MODAL
}