/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const GET_PARKING_SUB_LOTS_SUCCESS = 'manage/GET_PARKING_SUB_LOTS_SUCCESS';
const SET_PARKINGSUBLOT_TYPES = 'manage/SET_PARKINGSUBLOT_TYPES';
const SET_COLLECTION_MODELS = 'manage/SET_COLLECTION_MODELS';
const SET_PLATE_NUMBER_TYPES = 'manage/SET_PLATE_NUMBER_TYPES';
const SHOW_ADD_PARKINGSUBLOT_MODAL = 'manage/SHOW_ADD_PARKINGSUBLOT_MODAL';
const HIDE_ADD_PARKINGSUBLOT_MODAL = 'manage/HIDE_ADD_PARKINGSUBLOT_MODAL';
const SHOW_EDIT_PARKING_SUBLOT_MODAL = 'manage/SHOW_EDIT_PARKING_SUBLOT_MODAL ';
const HIDE_EDIT_PARKING_SUBLOT_MODAL = 'manage/HIDE_EDIT_PARKING_SUBLOT_MODAL ';
const GET_PARKING_SUBLOT_COUNT_SUCCESS = 'manage/GET_PARKING_SUBLOT_COUNT_SUCCESS';
const NEW_PARKING_SUBLOT_CREATED = 'manage/NEW_PARKING_SUBLOT_CREATED';
export default {
    GET_PARKING_SUB_LOTS_SUCCESS,
    SET_PARKINGSUBLOT_TYPES,
    SET_COLLECTION_MODELS,
    SET_PLATE_NUMBER_TYPES,
    SHOW_ADD_PARKINGSUBLOT_MODAL,
    HIDE_ADD_PARKINGSUBLOT_MODAL,
    GET_PARKING_SUBLOT_COUNT_SUCCESS,
    NEW_PARKING_SUBLOT_CREATED,
    SHOW_EDIT_PARKING_SUBLOT_MODAL,
    HIDE_EDIT_PARKING_SUBLOT_MODAL
};
