/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const GET_PARKING_LOTS_SUCCESS = 'manage/GET_PARKING_LOTS_SUCCESS';
const SHOW_ADD_PARKINGLOT_MODAL = 'manage/SHOW_ADD_PARKINGLOT_MODAL';
const HIDE_ADD_PARKINGLOT_MODAL = 'manage/HIDE_ADD_PARKINGLOT_MODAL';
const SHOW_EDIT_PARKINGLOT_MODAL = 'manage/SHOW_EDIT_PARKINGLOT_MODAL';
const HIDE_EDIT_PARKINGLOT_MODAL = 'manage/HIDE_EDIT_PARKINGLOT_MODAL';
const SET_PARKING_TYPES = 'manage/SET_PARKING_TYPES';
const SET_TICKETING_SYSTEMS = 'manage/SET_TICKETING_SYSTEMS';
const SET_PARKING_AREA_TYPES = 'manage/SET_PARKING_AREA_TYPES';
const SET_PARKING_LOT_COUNT = 'manage/SET_PARKING_LOT_COUNT';
const SHOW_PROGRESS_PARKING_LOTS = 'manage/SHOW_PROGRESS_PARKING_LOTS';
const HIDE_PROGRESS_PARKING_LOTS = 'manage/HIDE_PROGRESS_PARKING_LOTS';
const NEW_PARKING_LOT_ADDED = 'manage/NEW_PARKING_LOT_ADDED';
const NEW_PARKING_LOT_SEACH_SUGGESTIONS = '@@manage/NEW_PARKING_LOT_SEACH_SUGGESTIONS';
const CLEAR_PARKING_LOT_SEARCH_SUGGESTIONS = '@@manage/CLEAR_PARKING_LOT_SEARCH_SUGGESTIONS';
export default {
    GET_PARKING_LOTS_SUCCESS,
    SHOW_ADD_PARKINGLOT_MODAL,
    HIDE_ADD_PARKINGLOT_MODAL,
    SET_PARKING_TYPES,
    SET_TICKETING_SYSTEMS,
    SET_PARKING_AREA_TYPES,
    SHOW_EDIT_PARKINGLOT_MODAL,
    HIDE_EDIT_PARKINGLOT_MODAL,
    SET_PARKING_LOT_COUNT,
    SHOW_PROGRESS_PARKING_LOTS,
    HIDE_PROGRESS_PARKING_LOTS,
    NEW_PARKING_LOT_ADDED,
    NEW_PARKING_LOT_SEACH_SUGGESTIONS,
    CLEAR_PARKING_LOT_SEARCH_SUGGESTIONS
};

