/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const GET_PRICING_SLOTS = "pricing/GET_PRICING_SLOTS";
const GET_PRICING_GRIDS = "pricing/GET_PRICING_GRIDS";
const GET_PRICING_SLOTS_SUCCESS = "pricing/GET_PRICING_SLOTS_SUCCESS";
const SET_GRID_DURATION = 'pricing/SET_GRID_DURATION';
const SET_GRID_COST = 'pricing/SET_GRID_COST';
const SET_GRID_STRUCTURE = 'pricing/SET_GRID_STRUCTURE';
const SET_PRICING_TABLE_DATA = "pricing/SET_PRICING_TABLE_DATA";
const SET_DURATION_DATA = "pricing/SET_DURATION_DATA";
const SET_PRICING_STATE = "pricing/SET_PRICING_STATE";
const NEW_PRICE_GRID_CREATED = "pricing/NEW_PRICE_GRID_CREATED";
const UPDATE_PRICING_TABLE_AFTER_PRICE_GRID_UPDATE = "pricing/UPDATE_PRICING_TABLE_AFTER_PRICE_GRID_UPDATE";
const CLEAR_PRICING_STATE = "pricing/CLEAR_PRICING_STATE";
const HIDE_ADD_PRICE_GRID_OPTION = "pricing/HIDE_ADD_PRICE_GRID_OPTION";
const REMOVE_PRICE_GRID = "pricing/REMOVE_PRICE_GRID";
export default {
    SET_PRICING_TABLE_DATA,
    GET_PRICING_SLOTS,
    GET_PRICING_GRIDS,
    GET_PRICING_SLOTS_SUCCESS,
    SET_GRID_DURATION,
    SET_GRID_COST,
    SET_GRID_STRUCTURE,
    SET_DURATION_DATA,
    SET_PRICING_STATE,
    UPDATE_PRICING_TABLE_AFTER_PRICE_GRID_UPDATE,
    NEW_PRICE_GRID_CREATED,
    CLEAR_PRICING_STATE,
    HIDE_ADD_PRICE_GRID_OPTION,
    REMOVE_PRICE_GRID
};
