/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const GET_USERS_SUCCESS = 'user/GET_USERS_SUCCESS';
const GET_USERS_ACCESS_SUCCESS = 'user/GET_USERS_ACCESS_SUCCESS';
const GET_COMPANY_SUCCESS = 'user/GET_COMPANY_SUCCESS';
const GET_ALL_USER_PERMISSION_SUCCESS = 'user/GET_ALL_USER_PERMISSION_SUCCESS';
const GET_USER_PERMISSION_SUCCESS = 'user/GET_USER_PERMISSION_SUCCESS';
const GET_USER_PARKING_SUBLOT_ACCESS_SUCCESS = "user/GET_USER_PARKING_SUBLOT_ACCESS_SUCCESS";
const COMPANY_SELECTED_FROM_DROPDOWN = "user/COMPANY_SELECTED_FROM_DROPDOWN";
const PARKING_SELECTED_FROM_DROPDOWN = "user/PARKING_SELECTED_FROM_DROPDOWN";
const PARKING_LOT_SELECTED_FROM_DROPDOWN = "user/PARKING_LOT_SELECTED_FROM_DROPDOWN";
const PARKING_SUBLOT_CHECKBOX_TOGGLED = "user/PARKING_SUBLOT_CHECKBOX_TOGGLED";
const USER_ACCESS_CHECKBOX_TOGGLED = "user/USER_ACCESS_CHECKBOX_TOGGLED";
const CLEAR_SELECTED_PARKING_SUBLOTS = "user/CLEAR_SELECTED_PARKING_SUBLOTS";
const SHOW_ADD_PARKING_SUBLOT_ACCESS_PROGRESS = "user/SHOW_ADD_PARKING_SUBLOT_ACCESS_PROGRESS";
const HIDE_ADD_PARKING_SUBLOT_ACCESS_PROGRESS = "user/HIDE_ADD_PARKING_SUBLOT_ACCESS_PROGRESS";
const SHOW_USER_ACCESS_SUCCESS_PROGRESS = "user/SHOW_USER_ACCESS_SUCCESS_PROGRESS";
const HIDE_USER_ACCESS_SUCCESS_PROGRESS = "user/HIDE_USER_ACCESS_SUCCESS_PROGRESS";
const PARKING_SUBLOT_ACCESSES_ADDED = "user/PARKING_SUBLOT_ACCESSES_ADDED";
const USER_ACCESS_LIST_UPDATED = "user/USER_ACCESS_LIST_UPDATED";
const PARKING_SUBLOTS_ACCESSES_DELETED = "user/PARKING_SUBLOTS_ACCESSES_DELETED";
const GET_USER_B2B_COUNT_SUCCESS = '@@user/GET_USER_B2B_COUNT_SUCCESS';
const GET_USER_B2B_DATA = '@@user/GET_USER_B2B_DATA';
const SHOW_USER_B2B_DATA_FETCH_PROGRESS = '@@user/SHOW_USER_B2B_DATA_FETCH_PROGRESS';
const HIDE_USER_B2B_DATA_FETCH_PROGRESS = '@@user/HIDE_USER_B2B_DATA_FETCH_PROGRESS';
const NEW_USER_CREATED = '@@user/NEW_USER_CREATED';
const FETCH_SEARCH_SUGGESTION_SUCCESS = '@@user/FETCH_SEARCH_SUGGESTION_SUCCESS';
const CLEAR_SEARCH_SUGGESTIONS = '@@user/CLEAR_SEARCH_SUGGESTIONS';
export default {
    GET_USERS_SUCCESS,
    GET_USERS_ACCESS_SUCCESS,
    GET_COMPANY_SUCCESS,
    GET_USER_PERMISSION_SUCCESS,
    GET_ALL_USER_PERMISSION_SUCCESS,
    GET_USER_PARKING_SUBLOT_ACCESS_SUCCESS,
    COMPANY_SELECTED_FROM_DROPDOWN,
    PARKING_SELECTED_FROM_DROPDOWN,
    PARKING_LOT_SELECTED_FROM_DROPDOWN,
    PARKING_SUBLOT_CHECKBOX_TOGGLED,
    USER_ACCESS_CHECKBOX_TOGGLED,
    CLEAR_SELECTED_PARKING_SUBLOTS,
    SHOW_ADD_PARKING_SUBLOT_ACCESS_PROGRESS,
    HIDE_ADD_PARKING_SUBLOT_ACCESS_PROGRESS,
    SHOW_USER_ACCESS_SUCCESS_PROGRESS, HIDE_USER_ACCESS_SUCCESS_PROGRESS,
    PARKING_SUBLOT_ACCESSES_ADDED,
    USER_ACCESS_LIST_UPDATED,
    PARKING_SUBLOTS_ACCESSES_DELETED,
    GET_USER_B2B_COUNT_SUCCESS,
    GET_USER_B2B_DATA,
    SHOW_USER_B2B_DATA_FETCH_PROGRESS,
    HIDE_USER_B2B_DATA_FETCH_PROGRESS,
    NEW_USER_CREATED,
    CLEAR_SEARCH_SUGGESTIONS,
    FETCH_SEARCH_SUGGESTION_SUCCESS
};
