/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const SHOW_COMPANY_EDIT_MODAL = "manage/company/SHOW_COMPANY_EDIT_MODAL";
const HIDE_COMPANY_EDIT_MODAL = "manage/company/HIDE_COMPANY_EDIT_MODAL";
const SET_COMPANY_EDIT_MODAL = "manage/company/SET_COMPANY_EDIT_MODAL";
const UPDATE_COMPANY_NAME = "manage/company/UPDATE_COMPANY_NAME";
const UPDATE_COMPANY_ADDRESS = "manage/company/UPDATE_COMPANY_ADDRESS";
const UPDATE_COMPANY_CITY = "manage/company/UPDATE_COMPANY_CITY";
const UPDATE_COMPANY_CONTRACTOR = "manage/company/UPDATE_COMPANY_CONTRACTOR";
const UPDATE_COMPANY_EMAIL = "manage/company/UPDATE_COMPANY_EMAIL";
const UPDATE_COMPANY_CONTACTNUMBER = "manage/company/UPDATE_COMPANY_CONTACTNUMBER";
const UPDATE_COMPANY_WEBSITE = "manage/company/UPDATE_COMPANY_WEBSITE";
const UPDATE_FREECHARGE_MERCHANT_ID = "manage/company/UPDATE_FREECHARGE_MERCHANT_ID";
const UPDATE_COMPANY_INFORMATION = "manage/company/UPDATE_COMPANY_INFORMATION";


export default {
	SHOW_COMPANY_EDIT_MODAL, 
	HIDE_COMPANY_EDIT_MODAL, 
	SET_COMPANY_EDIT_MODAL, 
	UPDATE_COMPANY_NAME,
	UPDATE_COMPANY_ADDRESS,
	UPDATE_COMPANY_CITY,
	UPDATE_COMPANY_CONTRACTOR,
	UPDATE_COMPANY_EMAIL,
	UPDATE_COMPANY_CONTACTNUMBER,
	UPDATE_COMPANY_WEBSITE,UPDATE_FREECHARGE_MERCHANT_ID,
	UPDATE_COMPANY_INFORMATION
};

