/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const GET_PARKINGS_SUCCESS = 'manage/GET_PARKINGS_SUCCESS';
const SHOW_EDIT_PARKING_MODAL = 'manage/SHOW_EDIT_PARKING_MODAL';
const SET_PARKING_CATEGORIES = 'manage/SET_PARKING_CATEGORIES';
const SET_PARKING_BOOKING_STATES = 'manage/SET_PARKING_BOOKING_STATES';
const SET_TOTAL_PARKING_COUNT = 'manage/SET_TOTAL_PARKING_COUNT';
const HIDE_ADD_PARKING_MODAL = "manage/HIDE_ADD_PARKING_MODAL";
const SHOW_ADD_PARKING_MODAL = "manage/SHOW_ADD_PARKING_MODAL";
const NEW_PARKING_ADDED = "manage/NEW_PARKING_ADDED";
const HIDE_EDIT_PARKING_MODAL = "manage/HIDE_EDIT_PARKING_MODAL";
const PARKING_SUGGESTIONS_FETCH_SUCCESS = '@@manage/PARKING_SUGGESTIONS_FETCH_SUCCESS';
const PARKING_SUGGESTIONS_CLEAR = '@@manage/PARKING_SUGGESTIONS_CLEAR';
export default {
    GET_PARKINGS_SUCCESS,
    SHOW_EDIT_PARKING_MODAL,
    SET_PARKING_CATEGORIES,
    SET_PARKING_BOOKING_STATES,
    SET_TOTAL_PARKING_COUNT,
    HIDE_ADD_PARKING_MODAL,
    SHOW_ADD_PARKING_MODAL,
    NEW_PARKING_ADDED,
    HIDE_EDIT_PARKING_MODAL,
    PARKING_SUGGESTIONS_FETCH_SUCCESS,
    PARKING_SUGGESTIONS_CLEAR
};

