/**
 * Copyright  ( C )  2016-2017 GetMyParking - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential.
 */

const GET_RECEIPT_CONTENTS_SUCCESS = 'receiptContent/GET_RECEIPT_CONTENTS_SUCCESS';
const SHOW_VALUES_WNEN_FOCUS_GAINED = 'receiptContent/SHOW_VALUES_WNEN_FOCUS_GAINED';
const HIDE_VALUES_WNEN_BLUR_GAINED = 'receiptContent/HIDE_VALUES_WNEN_BLUR_GAINED';
const ON_CHANGE_RADIO_BUTTON = 'receiptContent/ON_CHANGE_RADIO_BUTTON';
const ON_CHANGE_RECEIPT_CONTENT = 'receiptContent/ON_CHANGE_RECEIPT_CONTENT';
const ON_SUBMIT_RECEIPT_CONTENT = 'receiptContent/ON_SUBMIT_RECEIPT_CONTENT';
const ON_CHANGE_RECEIPT_CONTENT_SEQUENCE = 'receiptContent/ON_CHANGE_RECEIPT_CONTENT_SEQUENCE';
const DELETE_RECEIPT_CONTENT = 'receiptContent/DELETE_RECEIPT_CONTENT';
const ADD_NEW_RECEIPT_CONTENT = 'receiptContent/ADD_NEW_RECEIPT_CONTENT';
const TOGGLE_DUPLICATE_RECIPT_CONTENT_MODAL = 'receiptContent/TOGGLE_DUPLICATE_RECIPT_CONTENT_MODAL';

export default { 
	GET_RECEIPT_CONTENTS_SUCCESS, 
	SHOW_VALUES_WNEN_FOCUS_GAINED, 
	HIDE_VALUES_WNEN_BLUR_GAINED, 
	ON_CHANGE_RADIO_BUTTON, 
	ON_CHANGE_RECEIPT_CONTENT,
	ON_SUBMIT_RECEIPT_CONTENT,
	ON_CHANGE_RECEIPT_CONTENT_SEQUENCE,
	DELETE_RECEIPT_CONTENT,
	ADD_NEW_RECEIPT_CONTENT,
    TOGGLE_DUPLICATE_RECIPT_CONTENT_MODAL
};
